name: "Code Analysis"

on: [pull_request]
jobs:
  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - run: git checkout HEAD^2

    - name: Run Linter
      run: |
        docker run --rm -v $PWD:/app composer:2.6 sh -c \
        "composer install --profile --ignore-platform-reqs && composer check"