name: "Linter"

on: [pull_request]
jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Linter
      run: |
        docker run --rm -v $PWD:/app composer sh -c \
        "composer install --profile --ignore-platform-reqs && composer lint" 