name: Tests

on: [pull_request]

jobs:
  tests: 
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Docker Compose
        run: |
          docker-compose up -d
          sleep 5

      - name: Run Tests
        run: |
          docker-compose exec web vendor/bin/phpunit --configuration phpunit.xml